### ISSUE TITLE
what happens to an existing column

### ISSUE THREAD

**Issue by samnissen** [sshaw/keep_defaults#1]
Please can you document what happens to mature applications. For instance, you have:

```ruby
Order.last.taxes #=> nil
```

and you add a default

```ruby
change_column :orders, :taxes, :integer, :default => 0
```

what happens when you add `KeepDefaults` and run the first code block again?

**Comment by sshaw** [comment]
The module will keep the default if the column has one and does not allow null.

Given your example It appears  null is allowed.

**Comment by sshaw** [comment]
Docs say:

    ... attributes for not null columns with default values from being set to nil.

What do you suggest to make things clearer?

**Comment by samnissen** [comment]
I am going through this trying to figure out what I would need to add this to my applications. And one of those things is getting a bit of confidence about what will happen to them. So I'd suggest something like a cleaned up version of this in the README:

```ruby
Order.last.taxes #=> nil
# ...
change_column :orders, :taxes, :integer, :default => 0
# ...
include KeepDefaults
# ...
Order.last.taxes #=> nil
```

**Comment by sshaw** [comment]
How about this? https://github.com/sshaw/keep_defaults/tree/doc-updates#using-with-an-existing-column

**Comment by samnissen** [comment]
Thanks for this, @sshaw. I think that answers the question, and allows someone to reverse engineer behavior. I'm always in favor of code examples, though, and would love to see a section on "here's what happens when you don't do this recommended action", and for that section to be dominated by a code block.
