### ISSUE TITLE
Feature request: Add a keep_defaults version of `unscoped`

### ISSUE THREAD

**Issue by samnissen** [sshaw/keep_defaults#2]
```ruby
class Order < ActiveRecord::Base
  include `KeepDefaults`
end
```

```ruby
Order.create!(taxes: nil)
Order.last.taxes #=> 0
Order.remove_defaults.last.taxes #=> nil
```

**Comment by sshaw** [comment]
Fun idea but what is the use case?

**Comment by samnissen** [comment]
As with my other issue, I'm trying to increase my comfort level with a gem that creates a layer between me and my database. One of those things that will increase my confidence is the ability to interrogate through ActiveRecord what the _actual_ state of my database is, hence the feature request.

I'd also love to see some way of ignoring defaults at an attribute level, like:

```ruby
class Order
  remove_defaults :taxes
  # ...
end
# ...
Order.last.taxes #=> nil
```

**Comment by sshaw** [comment]
> my confidence is the ability to interrogate through ActiveRecord what the actual state of my database is

This is possible with and without this gem. This gem just ensures one cannot override a DB default with `nil`. 

> I'd also love to see some way of ignoring defaults at an attribute level, like:

I considered this but time will tell as to whether it's a worthwhile feature. Pull requests are welcome!
